### ISSUE TITLE
Investigate transition from Grunt to Gulp

### ISSUE THREAD

**Issue by Fauntleroy** [solidusjs/solidus-site-template#15]
[Gulp.js](http://gulpjs.com/) is the new big name in asset compilation with node.js. It leverages Streams to greatly increase the speed of compilation, while using a more direct (less giant-object-of-config) approach. I think it's worth investigating a transition to Gulp for the speed increase alone; many people have reported compilation times going from seconds to milliseconds after switching. With our require.js compilations sometimes taking upwards of 4 or 5 seconds, I think it's important that we try and get them speedier to make development easier.

**Comment by localjo** [comment]
New solidus template here: https://github.com/SparkartGroupInc/solidus-starter-site/
And Slush generator here: https://github.com/SparkartGroupInc/slush-solidus
